# Air configuration for Go backend live reload
root = "."
include_ext = ["go"]
exclude_dir = ["vendor", "frontend", "dist", "node_modules"]
include_dir = ["cmd", "internal"]
delay = 200
stop_on_error = true

[build]
  bin = "./bin/server"
  cmd = "go build -o ./bin/server ./cmd/server"
  include_ext = ["go"]
  exclude_dir = ["vendor", "frontend", "dist", "node_modules"]
  include_dir = ["cmd", "internal"]
  follow_symlink = true
  send_interrupt = true
  kill_delay = 500

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true
