# typed: false
# frozen_string_literal: true

# Homebrew formula for node-stats. Auto-generated by scripts/gen-homebrew-formula.sh
# on each release — do not edit by hand.
#
#   brew tap lastskywalkerer/node-page https://github.com/LastSkywalkerER/node-page
#   brew install node-stats
class NodeStats < Formula
  desc "Self-hosted system monitoring dashboard (CPU/mem/disk/net/Docker)"
  homepage "https://github.com/LastSkywalkerER/node-page"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/LastSkywalkerER/node-page/releases/download/v#{version}/node-stats_v#{version}_darwin_arm64.tar.gz"
      sha256 "328700d5fa69062921593bad4efb4632f5a6b264a37aa1387d1c8ed2292a4825"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/LastSkywalkerER/node-page/releases/download/v#{version}/node-stats_v#{version}_linux_amd64.tar.gz"
      sha256 "eaca3685cd5fc1625cc19a9f4c18272f858d2a9649c49642490dc95f2db9c50e"
    end
    on_arm do
      url "https://github.com/LastSkywalkerER/node-page/releases/download/v#{version}/node-stats_v#{version}_linux_arm64.tar.gz"
      sha256 "15135b84037457ec95f3e96061da6c5c2f1e82ad6b694f85c8aa816f17f0b1bd"
    end
  end

  def install
    bin.install "node-stats"
  end

  test do
    assert_match "System Stats", shell_output("#{bin}/node-stats -help")
  end
end
