package gateway

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v2"
)

// Traefik v3 file-provider dynamic configuration shapes (only the subset we
// emit). Field names follow Traefik's YAML exactly.
type traefikDynamic struct {
	HTTP traefikHTTP `yaml:"http"`
	TCP  *traefikTCP `yaml:"tcp,omitempty"`
}

// TCP section — used for TLS passthrough routes (SNI-routed raw TLS).
type traefikTCP struct {
	Routers  map[string]traefikTCPRouter  `yaml:"routers,omitempty"`
	Services map[string]traefikTCPService `yaml:"services,omitempty"`
}

type traefikTCPRouter struct {
	Rule        string         `yaml:"rule"`
	Service     string         `yaml:"service"`
	EntryPoints []string       `yaml:"entryPoints"`
	Priority    int            `yaml:"priority,omitempty"`
	TLS         *traefikTCPTLS `yaml:"tls,omitempty"`
}

type traefikTCPTLS struct {
	Passthrough bool `yaml:"passthrough"`
}

type traefikTCPService struct {
	LoadBalancer traefikTCPLoadBalancer `yaml:"loadBalancer"`
}

type traefikTCPLoadBalancer struct {
	Servers []traefikTCPServer `yaml:"servers"`
}

type traefikTCPServer struct {
	Address string `yaml:"address"`
}

type traefikHTTP struct {
	Routers     map[string]traefikRouter     `yaml:"routers,omitempty"`
	Services    map[string]traefikService    `yaml:"services,omitempty"`
	Middlewares map[string]traefikMiddleware `yaml:"middlewares,omitempty"`

	// ServersTransports carries per-route upstream TLS settings (skip-verify
	// for self-signed https targets).
	ServersTransports map[string]traefikServersTransport `yaml:"serversTransports,omitempty"`
}

type traefikRouter struct {
	Rule        string      `yaml:"rule"`
	Service     string      `yaml:"service"`
	EntryPoints []string    `yaml:"entryPoints"`
	Middlewares []string    `yaml:"middlewares,omitempty"`
	Priority    int         `yaml:"priority,omitempty"`
	TLS         *traefikTLS `yaml:"tls,omitempty"`
}

type traefikTLS struct {
	CertResolver string `yaml:"certResolver,omitempty"`
}

type traefikService struct {
	LoadBalancer traefikLoadBalancer `yaml:"loadBalancer"`
}

type traefikLoadBalancer struct {
	Servers          []traefikServer `yaml:"servers"`
	PassHostHeader   *bool           `yaml:"passHostHeader,omitempty"`
	ServersTransport string          `yaml:"serversTransport,omitempty"`
}

type traefikServer struct {
	URL string `yaml:"url"`
}

type traefikServersTransport struct {
	InsecureSkipVerify bool                       `yaml:"insecureSkipVerify"`
	ForwardingTimeouts *traefikForwardingTimeouts `yaml:"forwardingTimeouts,omitempty"`
}

type traefikForwardingTimeouts struct {
	// ResponseHeaderTimeout: how long to wait for the upstream's response
	// headers (504 past it). Duration string ("60s").
	ResponseHeaderTimeout string `yaml:"responseHeaderTimeout,omitempty"`
}

type traefikMiddleware struct {
	BasicAuth      *traefikBasicAuth      `yaml:"basicAuth,omitempty"`
	IPAllowList    *traefikIPAllowList    `yaml:"ipAllowList,omitempty"`
	RedirectScheme *traefikRedirectScheme `yaml:"redirectScheme,omitempty"`
	InFlightReq    *traefikInFlightReq    `yaml:"inFlightReq,omitempty"`
	RateLimit      *traefikRateLimit      `yaml:"rateLimit,omitempty"`
	Buffering      *traefikBuffering      `yaml:"buffering,omitempty"`
}

// inFlightReq: at most Amount concurrent requests per source (client IP by
// default) — 429 above it.
type traefikInFlightReq struct {
	Amount int `yaml:"amount"`
}

// rateLimit: Average req/s per source with Burst headroom — 429 above it.
type traefikRateLimit struct {
	Average int `yaml:"average"`
	Burst   int `yaml:"burst"`
}

// buffering: 413 for request bodies above MaxRequestBodyBytes. Note it
// buffers responses too (verified against traefik v3.3: SSE arrives in one
// piece), so it is only rendered when a route explicitly asks for a cap.
type traefikBuffering struct {
	MaxRequestBodyBytes int64 `yaml:"maxRequestBodyBytes"`
}

type traefikBasicAuth struct {
	Users []string `yaml:"users"`
}

type traefikIPAllowList struct {
	SourceRange []string `yaml:"sourceRange"`
}

type traefikRedirectScheme struct {
	Scheme    string `yaml:"scheme"`
	Permanent bool   `yaml:"permanent"`
}

const (
	entryPointWeb       = "web"
	entryPointWebSecure = "websecure"
	// namePrefix namespaces every object node-stats owns so it can never
	// collide with the operator's routers/services in an adopted Traefik.
	namePrefix = "ns-"
	// ownershipHeader is the first line of every file node-stats writes; the
	// materializer only ever deletes files that start with it.
	ownershipHeader = OwnershipPrefix + " — do NOT edit by hand; changes are overwritten."
)

// OwnershipPrefix starts every file node-stats writes into a Traefik dynamic
// dir; the materializer refuses to delete anything that doesn't start with it.
const OwnershipPrefix = "# Generated by node-stats (gateway)"

// Rendered is the set of Traefik dynamic files node-stats owns. A nil slice
// means "that file must not exist" (the materializer removes it): Traefik's
// file provider logs "http cannot be a standalone element" for an empty
// `http: {}` document on every reload.
type Rendered struct {
	// Routes is DynamicFileName: every enabled route's routers/services/
	// middlewares, grouped by domain with an index in the header.
	Routes []byte
	// Blocks is BlocksFileName: the client deny list. Only rendered when there
	// is at least one route (an empty gateway serves nothing anyway) and at
	// least one unexpired block — it changes on its own rhythm (TTL sweeps),
	// so keeping it apart leaves the routes file untouched.
	Blocks []byte
}

// renderCtx accumulates, while the document is being built, everything the
// pretty-printer needs afterwards: the domain order of routes (so the YAML
// maps come out grouped by route instead of by opaque id) and a human comment
// per object.
type renderCtx struct {
	rank     map[string]int    // route id → position in the domain-sorted list
	comments map[string]string // object name → comment line
}

// Sections of the dynamic document; comments are keyed "<section>/<name>"
// because a route's router and service share the same object name.
const (
	secHTTPRouters     = "http.routers"
	secHTTPServices    = "http.services"
	secHTTPMiddlewares = "http.middlewares"
	secHTTPTransports  = "http.serversTransports"
	secTCPRouters      = "tcp.routers"
	secTCPServices     = "tcp.services"
)

func (rc *renderCtx) note(section, name, label, what string) {
	rc.comments[section+"/"+name] = label + " — " + what
}

// RenderFiles produces the Traefik dynamic YAML for the enabled routes and the
// block list. Output is deterministic (routes sorted by domain, then path;
// stable object names ns-<route_id>) so the materializer can diff bytes and
// only rewrite a file on real change.
//
// Per route:
//   - one service (loadBalancer → target URL), a serversTransport when it
//     needs skip-verify or an upstream timeout
//   - a router on `websecure` (tls) or `web` (plain)
//   - for TLS routes an extra `web` router redirecting to https
//   - optional middlewares: ipAllowList, rateLimit, inFlightReq, basicAuth,
//     buffering (in that order)
func RenderFiles(cfg Config, routes []Route, blocks []Block) (Rendered, error) {
	doc := newDynamic()
	sorted := append([]Route(nil), routes...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].Domain != sorted[j].Domain {
			return sortDomainKey(sorted[i].Domain) < sortDomainKey(sorted[j].Domain)
		}
		if sorted[i].PathPrefix != sorted[j].PathPrefix {
			return sorted[i].PathPrefix < sorted[j].PathPrefix
		}
		return sorted[i].RouteID < sorted[j].RouteID
	})
	rc := &renderCtx{rank: map[string]int{}, comments: map[string]string{}}
	for i, r := range sorted {
		rc.rank[r.RouteID] = i
	}

	for _, r := range sorted {
		if !r.Enabled || r.RouteID == "" || r.Domain == "" || r.TargetHost == "" || r.TargetPort <= 0 {
			continue
		}
		base := namePrefix + r.RouteID
		label := routeLabel(r)
		if r.IsPassthrough() {
			renderPassthrough(&doc, rc, base, label, r)
			continue
		}
		svcName := base
		scheme := r.TargetScheme
		if scheme == "" {
			scheme = SchemeHTTP
		}
		targetURL := fmt.Sprintf("%s://%s:%d", scheme, r.TargetHost, r.TargetPort)
		lb := traefikLoadBalancer{Servers: []traefikServer{{URL: targetURL}}}
		skipVerify := scheme == SchemeHTTPS && r.TargetInsecureSkipVerify
		if skipVerify || r.UpstreamTimeoutSeconds > 0 {
			tName := base + "-transport"
			tr := traefikServersTransport{InsecureSkipVerify: skipVerify}
			what := []string{}
			if skipVerify {
				what = append(what, "skip upstream cert verification")
			}
			if r.UpstreamTimeoutSeconds > 0 {
				tr.ForwardingTimeouts = &traefikForwardingTimeouts{ResponseHeaderTimeout: fmt.Sprintf("%ds", r.UpstreamTimeoutSeconds)}
				what = append(what, fmt.Sprintf("upstream response timeout %ds", r.UpstreamTimeoutSeconds))
			}
			doc.HTTP.ServersTransports[tName] = tr
			rc.note(secHTTPTransports, tName, label, strings.Join(what, ", "))
			lb.ServersTransport = tName
		}
		doc.HTTP.Services[svcName] = traefikService{LoadBalancer: lb}
		rc.note(secHTTPServices, svcName, label, "upstream "+targetURL)

		rule := hostRule(r.Domain)
		if p := strings.TrimSpace(r.PathPrefix); p != "" && p != "/" {
			rule += fmt.Sprintf(" && PathPrefix(`%s`)", p)
		}
		if r.ReadOnly {
			// Traefik v3's Method() takes exactly one argument — OR them.
			rule += " && " + readOnlyMethodsRule
		}

		// Middleware order: cheapest denials first (allow list, rate/concurrency
		// caps), then auth, then body buffering right before the upstream.
		var mws []string
		if r.IPAllowList != "" {
			name := base + "-ipallow"
			doc.HTTP.Middlewares[name] = traefikMiddleware{IPAllowList: &traefikIPAllowList{SourceRange: SplitCSV(r.IPAllowList)}}
			rc.note(secHTTPMiddlewares, name, label, "IP allow list")
			mws = append(mws, name)
		}
		if r.RateLimitRPS > 0 {
			name := base + "-ratelimit"
			doc.HTTP.Middlewares[name] = traefikMiddleware{RateLimit: &traefikRateLimit{Average: r.RateLimitRPS, Burst: 2 * r.RateLimitRPS}}
			rc.note(secHTTPMiddlewares, name, label, fmt.Sprintf("rate limit %d req/s per IP (burst %d)", r.RateLimitRPS, 2*r.RateLimitRPS))
			mws = append(mws, name)
		}
		if r.MaxConnsPerIP > 0 {
			name := base + "-inflight"
			doc.HTTP.Middlewares[name] = traefikMiddleware{InFlightReq: &traefikInFlightReq{Amount: r.MaxConnsPerIP}}
			rc.note(secHTTPMiddlewares, name, label, fmt.Sprintf("max %d concurrent requests per IP", r.MaxConnsPerIP))
			mws = append(mws, name)
		}
		if r.BasicAuthUsers != "" {
			name := base + "-auth"
			doc.HTTP.Middlewares[name] = traefikMiddleware{BasicAuth: &traefikBasicAuth{Users: SplitLines(r.BasicAuthUsers)}}
			rc.note(secHTTPMiddlewares, name, label, "basic auth")
			mws = append(mws, name)
		}
		if r.MaxBodyBytes > 0 {
			name := base + "-body"
			doc.HTTP.Middlewares[name] = traefikMiddleware{Buffering: &traefikBuffering{MaxRequestBodyBytes: r.MaxBodyBytes}}
			rc.note(secHTTPMiddlewares, name, label, fmt.Sprintf("max request body %s (buffered)", humanBytes(r.MaxBodyBytes)))
			mws = append(mws, name)
		}

		if r.TLS {
			tls := &traefikTLS{}
			if cfg.ACMEEnabled {
				tls.CertResolver = CertResolverName
			}
			doc.HTTP.Routers[base] = traefikRouter{
				Rule: rule, Service: svcName, EntryPoints: []string{entryPointWebSecure}, Middlewares: mws, TLS: tls,
			}
			rc.note(secHTTPRouters, base, label, "https router")
			// http → https redirect on the plain entrypoint. Kept as a separate
			// router so ACME HTTP-01 (served by Traefik itself, higher priority)
			// still works on `web`.
			redir := base + "-redirect"
			doc.HTTP.Middlewares[redir] = traefikMiddleware{RedirectScheme: &traefikRedirectScheme{Scheme: SchemeHTTPS, Permanent: true}}
			rc.note(secHTTPMiddlewares, redir, label, "http → https redirect")
			doc.HTTP.Routers[base+"-http"] = traefikRouter{
				Rule: rule, Service: svcName, EntryPoints: []string{entryPointWeb}, Middlewares: []string{redir},
			}
			rc.note(secHTTPRouters, base+"-http", label, "http router (redirects to https)")
		} else {
			doc.HTTP.Routers[base] = traefikRouter{
				Rule: rule, Service: svcName, EntryPoints: []string{entryPointWeb}, Middlewares: mws,
			}
			rc.note(secHTTPRouters, base, label, "http router")
		}
	}

	out := Rendered{}
	if len(doc.HTTP.Routers) == 0 && (doc.TCP == nil || len(doc.TCP.Routers) == 0) {
		// No enabled routes: no files at all (see Rendered).
		return out, nil
	}
	active := activeBlocks(blocks)

	body, err := emitYAML(doc, rc)
	if err != nil {
		return out, err
	}
	header := ownershipHeader + "\n# Manage routes in the node-stats admin panel → Gateway.\n"
	// Port hint for the Applications-view discovery parser (public URLs with
	// the gateway's actual published ports). Only managed mode knows them.
	if cfg.Mode == ModeManaged {
		hp, sp := cfg.HTTPPort, cfg.HTTPSPort
		if hp == 0 {
			hp = 80
		}
		if sp == 0 {
			sp = 443
		}
		header += fmt.Sprintf("# node-stats-gateway: http_port=%d https_port=%d\n", hp, sp)
	}
	header += routeIndex(sorted, len(active))
	out.Routes = append([]byte(header), body...)

	if len(active) > 0 {
		bdoc, brc := renderBlocksDoc(active, doc.TCP != nil && len(doc.TCP.Routers) > 0)
		bbody, err := emitYAML(bdoc, brc)
		if err != nil {
			return out, err
		}
		bheader := ownershipHeader + "\n# Blocked clients — every listed IP/CIDR gets 403 above every route (Gateway → Blocked clients).\n"
		bheader += blockIndex(active)
		out.Blocks = append([]byte(bheader), bbody...)
	}
	return out, nil
}

func newDynamic() traefikDynamic {
	return traefikDynamic{HTTP: traefikHTTP{
		Routers:           map[string]traefikRouter{},
		Services:          map[string]traefikService{},
		Middlewares:       map[string]traefikMiddleware{},
		ServersTransports: map[string]traefikServersTransport{},
	}}
}

// routeLabel is the human handle used in comments: "grafana.example.com" or
// "example.com/grafana".
func routeLabel(r Route) string {
	l := r.Domain
	if p := strings.TrimSpace(r.PathPrefix); p != "" && p != "/" {
		l += p
	}
	return oneLine(l)
}

// sortDomainKey orders hostnames by their reversed labels (example.com, then
// its subdomains together) and puts wildcards after concrete names.
func sortDomainKey(domain string) string {
	d := strings.TrimPrefix(domain, "*.")
	parts := strings.Split(d, ".")
	for i, j := 0, len(parts)-1; i < j; i, j = i+1, j-1 {
		parts[i], parts[j] = parts[j], parts[i]
	}
	key := strings.Join(parts, ".")
	if strings.HasPrefix(domain, "*.") {
		key += ".~" // '~' sorts after every hostname character
	}
	return key
}

// routeIndex is the header table: one line per route (disabled ones included,
// marked), so `head` on the file tells the whole story.
func routeIndex(sorted []Route, blockCount int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "#\n# Routes (%d):\n", len(sorted))
	width := 0
	for _, r := range sorted {
		if l := len([]rune(routeLabel(r))); l > width {
			width = l
		}
	}
	if width > 48 {
		width = 48
	}
	for _, r := range sorted {
		kind := "http"
		switch {
		case r.IsPassthrough():
			kind = "passthrough"
		case r.TLS:
			kind = "https"
		}
		var target string
		if r.IsPassthrough() {
			hp, sp := r.TargetPort, r.TargetHTTPSPort
			if hp <= 0 {
				hp = 80
			}
			if sp <= 0 {
				sp = 443
			}
			target = fmt.Sprintf("%s:%d (tls, sni) · :%d (http)", r.TargetHost, sp, hp)
		} else {
			scheme := r.TargetScheme
			if scheme == "" {
				scheme = SchemeHTTP
			}
			target = fmt.Sprintf("%s://%s:%d", scheme, r.TargetHost, r.TargetPort)
		}
		extras := routeExtras(r)
		line := fmt.Sprintf("#   %-*s  %-11s → %s", width, routeLabel(r), kind, oneLine(target))
		if n := oneLine(strings.TrimSpace(r.Name)); n != "" && n != r.Domain {
			line += " · " + n
		}
		if len(extras) > 0 {
			line += " · " + strings.Join(extras, ", ")
		}
		line += fmt.Sprintf("  [%s%s]", namePrefix, r.RouteID)
		if !r.Enabled {
			line += "  (disabled — not rendered)"
		}
		b.WriteString(line + "\n")
	}
	if blockCount > 0 {
		fmt.Fprintf(&b, "# Blocked clients: %d → %s\n", blockCount, BlocksFileName)
	}
	b.WriteString("#\n")
	return b.String()
}

// routeExtras summarises a route's access control + limits for the index.
func routeExtras(r Route) []string {
	if r.IsPassthrough() {
		return nil
	}
	var out []string
	if r.BasicAuthUsers != "" {
		out = append(out, fmt.Sprintf("basic auth (%d)", len(SplitLines(r.BasicAuthUsers))))
	}
	if r.IPAllowList != "" {
		out = append(out, "ip allow list")
	}
	if r.TargetInsecureSkipVerify && r.TargetScheme == SchemeHTTPS {
		out = append(out, "skip-verify")
	}
	if r.MaxConnsPerIP > 0 {
		out = append(out, fmt.Sprintf("%d concurrent/ip", r.MaxConnsPerIP))
	}
	if r.RateLimitRPS > 0 {
		out = append(out, fmt.Sprintf("%d req/s/ip", r.RateLimitRPS))
	}
	if r.UpstreamTimeoutSeconds > 0 {
		out = append(out, fmt.Sprintf("%ds upstream", r.UpstreamTimeoutSeconds))
	}
	if r.ReadOnly {
		out = append(out, "read-only")
	}
	if r.MaxBodyBytes > 0 {
		out = append(out, "≤ "+humanBytes(r.MaxBodyBytes)+" body")
	}
	return out
}

func blockIndex(active []Block) string {
	var b strings.Builder
	fmt.Fprintf(&b, "#\n# Blocked clients (%d):\n", len(active))
	width := 0
	for _, bl := range active {
		if len(bl.CIDR) > width {
			width = len(bl.CIDR)
		}
	}
	for _, bl := range active {
		until := "permanent"
		if bl.ExpiresAt != nil && !bl.ExpiresAt.IsZero() {
			until = "until " + bl.ExpiresAt.UTC().Format("2006-01-02 15:04 UTC")
		}
		line := fmt.Sprintf("#   %-*s  %s", width, bl.CIDR, until)
		if r := oneLine(strings.TrimSpace(bl.Reason)); r != "" {
			line += " · " + r
		}
		if by := oneLine(strings.TrimSpace(bl.CreatedBy)); by != "" {
			line += " · by " + by
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("#\n")
	return b.String()
}

// oneLine keeps operator-supplied text from breaking out of a YAML comment.
func oneLine(s string) string {
	return strings.Join(strings.Fields(strings.NewReplacer("\n", " ", "\r", " ").Replace(s)), " ")
}

func humanBytes(n int64) string {
	switch {
	case n >= 1<<30 && n%(1<<30) == 0:
		return fmt.Sprintf("%d GiB", n>>30)
	case n >= 1<<20 && n%(1<<20) == 0:
		return fmt.Sprintf("%d MiB", n>>20)
	case n >= 1<<10 && n%(1<<10) == 0:
		return fmt.Sprintf("%d KiB", n>>10)
	default:
		return fmt.Sprintf("%d B", n)
	}
}

// emitYAML marshals the document with every object map ordered by route (the
// domain-sorted rank, then name) instead of yaml's alphabetical-by-id order,
// and inserts one comment line above each object node-stats can describe.
func emitYAML(doc traefikDynamic, rc *renderCtx) ([]byte, error) {
	rank := func(name string) int {
		// name = ns-<route_id>[-suffix]; blocklist objects have no route.
		rest := strings.TrimPrefix(name, namePrefix)
		id := rest
		if i := strings.IndexByte(rest, '-'); i > 0 {
			id = rest[:i]
		}
		if r, ok := rc.rank[id]; ok {
			return r
		}
		return 1 << 30
	}
	http := yaml.MapSlice{}
	if len(doc.HTTP.Routers) > 0 {
		http = append(http, yaml.MapItem{Key: "routers", Value: ordered(doc.HTTP.Routers, rank)})
	}
	if len(doc.HTTP.Services) > 0 {
		http = append(http, yaml.MapItem{Key: "services", Value: ordered(doc.HTTP.Services, rank)})
	}
	if len(doc.HTTP.Middlewares) > 0 {
		http = append(http, yaml.MapItem{Key: "middlewares", Value: ordered(doc.HTTP.Middlewares, rank)})
	}
	if len(doc.HTTP.ServersTransports) > 0 {
		http = append(http, yaml.MapItem{Key: "serversTransports", Value: ordered(doc.HTTP.ServersTransports, rank)})
	}
	top := yaml.MapSlice{}
	if len(http) > 0 {
		top = append(top, yaml.MapItem{Key: "http", Value: http})
	}
	if doc.TCP != nil && len(doc.TCP.Routers) > 0 {
		tcp := yaml.MapSlice{
			{Key: "routers", Value: ordered(doc.TCP.Routers, rank)},
			{Key: "services", Value: ordered(doc.TCP.Services, rank)},
		}
		top = append(top, yaml.MapItem{Key: "tcp", Value: tcp})
	}
	raw, err := yaml.Marshal(top)
	if err != nil {
		return nil, err
	}
	return annotate(raw, rc.comments), nil
}

// ordered turns an object map into a yaml.MapSlice sorted by (rank, name).
func ordered[T any](m map[string]T, rank func(string) int) yaml.MapSlice {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		ri, rj := rank(keys[i]), rank(keys[j])
		if ri != rj {
			return ri < rj
		}
		return keys[i] < keys[j]
	})
	out := make(yaml.MapSlice, 0, len(keys))
	for _, k := range keys {
		out = append(out, yaml.MapItem{Key: k, Value: m[k]})
	}
	return out
}

// Line shapes in the marshaled document: top-level "http:" / "tcp:" (indent
// 0), a section "  routers:" (indent 2), an object "    ns-<id>:" (indent 4).
var (
	topKeyRe     = regexp.MustCompile(`^([a-z]+):$`)
	sectionKeyRe = regexp.MustCompile(`^  ([A-Za-z]+):$`)
	objectKeyRe  = regexp.MustCompile(`^    (` + namePrefix + `[A-Za-z0-9_-]+):$`)
)

// annotate inserts "    # <comment>" above every object that has one, plus a
// blank line between objects so each route reads as a block.
func annotate(raw []byte, comments map[string]string) []byte {
	lines := strings.Split(strings.TrimRight(string(raw), "\n"), "\n")
	var b strings.Builder
	top, section := "", ""
	for i, line := range lines {
		if m := topKeyRe.FindStringSubmatch(line); m != nil {
			top, section = m[1], ""
		} else if m := sectionKeyRe.FindStringSubmatch(line); m != nil {
			section = m[1]
		} else if m := objectKeyRe.FindStringSubmatch(line); m != nil {
			if i > 0 && strings.HasPrefix(lines[i-1], "      ") {
				b.WriteString("\n")
			}
			if c, ok := comments[top+"."+section+"/"+m[1]]; ok && c != "" {
				b.WriteString("    # " + c + "\n")
			}
		}
		b.WriteString(line)
		b.WriteString("\n")
	}
	return []byte(b.String())
}

// readOnlyMethodsRule is the rule fragment for ReadOnly routes. Traefik v3
// rejects `Method(`GET`,`HEAD`)` ("unexpected number of parameters"), hence
// the OR chain.
const readOnlyMethodsRule = "(Method(`GET`) || Method(`HEAD`) || Method(`OPTIONS`))"

// blockRouterPriority puts the deny routers above every route router (Traefik
// otherwise ranks by rule length, and a long Host rule could shadow the block).
const blockRouterPriority = 1_000_000

// activeBlocks drops expired/blank/duplicate entries and sorts the rest.
func activeBlocks(blocks []Block) []Block {
	now := time.Now().UTC()
	seen := map[string]struct{}{}
	var out []Block
	for _, b := range blocks {
		if b.Expired(now) || b.CIDR == "" {
			continue
		}
		if _, dup := seen[b.CIDR]; dup {
			continue
		}
		seen[b.CIDR] = struct{}{}
		out = append(out, b)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].CIDR < out[j].CIDR })
	if len(out) > MaxBlocks {
		out = out[:MaxBlocks]
	}
	return out
}

// renderBlocksDoc builds the blocklist document: catch-all routers (one per
// entrypoint) matching the blocked ClientIPs, rejected with 403 by an
// ipAllowList that can never match, so the request dies before any route
// middleware or upstream. TCP passthrough connections from blocked IPs are
// routed to a blackhole (connection reset) since raw TLS can't carry a 403 —
// only when the routes file has TCP routers at all.
func renderBlocksDoc(active []Block, hasTCP bool) (traefikDynamic, *renderCtx) {
	doc := newDynamic()
	rc := &renderCtx{rank: map[string]int{}, comments: map[string]string{}}
	parts := make([]string, len(active))
	for i, b := range active {
		parts[i] = fmt.Sprintf("ClientIP(`%s`)", b.CIDR)
	}
	rule := strings.Join(parts, " || ")

	deny := namePrefix + "blocked"
	bh := namePrefix + "blackhole"
	doc.HTTP.Middlewares[deny] = traefikMiddleware{IPAllowList: &traefikIPAllowList{SourceRange: []string{"255.255.255.255/32"}}}
	rc.comments[secHTTPMiddlewares+"/"+deny] = "blocklist — an allow list nothing matches: every blocked client gets 403"
	// Never dialed: the middleware rejects first. Port 9 = discard.
	doc.HTTP.Services[bh] = traefikService{LoadBalancer: traefikLoadBalancer{Servers: []traefikServer{{URL: "http://127.0.0.1:9"}}}}
	rc.comments[secHTTPServices+"/"+bh] = "blocklist — placeholder upstream, never dialed"
	doc.HTTP.Routers[namePrefix+"blocklist-http"] = traefikRouter{
		Rule: rule, Service: bh, EntryPoints: []string{entryPointWeb},
		Middlewares: []string{deny}, Priority: blockRouterPriority,
	}
	rc.comments[secHTTPRouters+"/"+namePrefix+"blocklist-http"] = "blocklist — catches blocked client IPs on :80 before any route"
	doc.HTTP.Routers[namePrefix+"blocklist-https"] = traefikRouter{
		Rule: rule, Service: bh, EntryPoints: []string{entryPointWebSecure},
		Middlewares: []string{deny}, Priority: blockRouterPriority, TLS: &traefikTLS{},
	}
	rc.comments[secHTTPRouters+"/"+namePrefix+"blocklist-https"] = "blocklist — same on :443"
	if hasTCP {
		doc.TCP = &traefikTCP{Routers: map[string]traefikTCPRouter{}, Services: map[string]traefikTCPService{}}
		doc.TCP.Services[bh] = traefikTCPService{LoadBalancer: traefikTCPLoadBalancer{
			Servers: []traefikTCPServer{{Address: "127.0.0.1:9"}},
		}}
		doc.TCP.Routers[namePrefix+"blocklist"] = traefikTCPRouter{
			Rule: "HostSNI(`*`) && (" + rule + ")", Service: bh,
			EntryPoints: []string{entryPointWebSecure}, Priority: blockRouterPriority,
			TLS: &traefikTCPTLS{Passthrough: true},
		}
		rc.comments[secTCPRouters+"/"+namePrefix+"blocklist"] = "blocklist — TLS passthrough connections from blocked IPs are reset (no 403 possible on raw TLS)"
	}
	return doc, rc
}

// hostRule builds the HTTP router rule for a domain: Host() for an exact name,
// HostRegexp() for a "*." wildcard (direct subdomains).
func hostRule(domain string) string {
	if strings.HasPrefix(domain, "*.") {
		return fmt.Sprintf("HostRegexp(`^[^.]+\\.%s$`)", regexp.QuoteMeta(domain[2:]))
	}
	return fmt.Sprintf("Host(`%s`)", domain)
}

// hostSNIRule is the TCP-router counterpart of hostRule.
func hostSNIRule(domain string) string {
	if strings.HasPrefix(domain, "*.") {
		return fmt.Sprintf("HostSNIRegexp(`^[^.]+\\.%s$`)", regexp.QuoteMeta(domain[2:]))
	}
	return fmt.Sprintf("HostSNI(`%s`)", domain)
}

// renderPassthrough emits the two halves of a delegation route: a TCP
// passthrough router on websecure (the other proxy terminates TLS itself) and a
// plain HTTP router on web to its http port (ACME HTTP-01 + redirects).
func renderPassthrough(doc *traefikDynamic, rc *renderCtx, base, label string, r Route) {
	httpPort := r.TargetPort
	if httpPort <= 0 {
		httpPort = 80
	}
	httpsPort := r.TargetHTTPSPort
	if httpsPort <= 0 {
		httpsPort = 443
	}
	if doc.TCP == nil {
		doc.TCP = &traefikTCP{Routers: map[string]traefikTCPRouter{}, Services: map[string]traefikTCPService{}}
	}
	tcpName := base + "-tls"
	tlsAddr := fmt.Sprintf("%s:%d", r.TargetHost, httpsPort)
	doc.TCP.Services[tcpName] = traefikTCPService{LoadBalancer: traefikTCPLoadBalancer{
		Servers: []traefikTCPServer{{Address: tlsAddr}},
	}}
	rc.note(secTCPServices, tcpName, label, "raw TLS to the other proxy at "+tlsAddr)
	rc.note(secTCPRouters, tcpName, label, "passthrough — :443 routed by SNI, TLS untouched")
	doc.TCP.Routers[tcpName] = traefikTCPRouter{
		Rule: hostSNIRule(r.Domain), Service: tcpName, EntryPoints: []string{entryPointWebSecure},
		TLS: &traefikTCPTLS{Passthrough: true},
	}
	httpName := base + "-http"
	httpURL := fmt.Sprintf("http://%s:%d", r.TargetHost, httpPort)
	doc.HTTP.Services[httpName] = traefikService{LoadBalancer: traefikLoadBalancer{
		Servers: []traefikServer{{URL: httpURL}},
	}}
	doc.HTTP.Routers[httpName] = traefikRouter{
		Rule: hostRule(r.Domain), Service: httpName, EntryPoints: []string{entryPointWeb},
	}
	rc.note(secHTTPRouters, httpName, label, "passthrough — :80 proxied as HTTP to "+httpURL+" (ACME challenges, redirects)")
	rc.note(secHTTPServices, httpName, label, "http upstream "+httpURL)
}

// SplitCSV splits a comma list, trimming blanks.
func SplitCSV(s string) []string {
	var out []string
	for _, p := range strings.Split(s, ",") {
		if t := strings.TrimSpace(p); t != "" {
			out = append(out, t)
		}
	}
	return out
}

// SplitLines splits on newlines, trimming blanks.
func SplitLines(s string) []string {
	var out []string
	for _, p := range strings.Split(s, "\n") {
		if t := strings.TrimSpace(p); t != "" {
			out = append(out, t)
		}
	}
	return out
}
