package gateway

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v2"
)

func TestRender_TLSRouteEmitsRedirectAndResolver(t *testing.T) {
	cfg := Config{Enabled: true, Mode: ModeManaged, ACMEEnabled: true}
	routes := []Route{{
		RouteID: "abc123", Domain: "grafana.example.com", TargetScheme: "http",
		TargetHost: "10.0.0.5", TargetPort: 3000, TLS: true, Enabled: true,
		IPAllowList: "10.0.0.0/8, 192.168.1.0/24", BasicAuthUsers: "admin:$2a$10$hash",
	}}
	out, err := Render(cfg, routes, nil)
	if err != nil {
		t.Fatal(err)
	}
	s := string(out)
	if !strings.HasPrefix(s, "# Generated by node-stats (gateway)") {
		t.Fatalf("missing ownership header:\n%s", s)
	}
	var doc traefikDynamic
	if err := yaml.Unmarshal(out, &doc); err != nil {
		t.Fatalf("output is not valid yaml: %v\n%s", err, s)
	}
	r, ok := doc.HTTP.Routers["ns-abc123"]
	if !ok {
		t.Fatalf("missing main router: %s", s)
	}
	if r.Rule != "Host(`grafana.example.com`)" || r.EntryPoints[0] != "websecure" || r.TLS == nil || r.TLS.CertResolver != "le" {
		t.Errorf("bad main router: %+v", r)
	}
	if len(r.Middlewares) != 2 || r.Middlewares[0] != "ns-abc123-ipallow" || r.Middlewares[1] != "ns-abc123-auth" {
		t.Errorf("middlewares: %v", r.Middlewares)
	}
	redir, ok := doc.HTTP.Routers["ns-abc123-http"]
	if !ok || redir.EntryPoints[0] != "web" || redir.Middlewares[0] != "ns-abc123-redirect" {
		t.Errorf("bad redirect router: %+v", redir)
	}
	if got := doc.HTTP.Services["ns-abc123"].LoadBalancer.Servers[0].URL; got != "http://10.0.0.5:3000" {
		t.Errorf("service url = %q", got)
	}
	if mw := doc.HTTP.Middlewares["ns-abc123-ipallow"]; mw.IPAllowList == nil || len(mw.IPAllowList.SourceRange) != 2 {
		t.Errorf("ipallow: %+v", mw)
	}
	if mw := doc.HTTP.Middlewares["ns-abc123-auth"]; mw.BasicAuth == nil || mw.BasicAuth.Users[0] != "admin:$2a$10$hash" {
		t.Errorf("auth: %+v", mw)
	}
}

func TestRender_PlainRouteSkipsDisabledAndIsDeterministic(t *testing.T) {
	cfg := Config{Enabled: true, Mode: ModeExternal}
	routes := []Route{
		{RouteID: "b", Domain: "b.example.com", TargetHost: "h", TargetPort: 80, Enabled: true, PathPrefix: "/api"},
		{RouteID: "a", Domain: "a.example.com", TargetHost: "h", TargetPort: 81, Enabled: false},
		{RouteID: "c", Domain: "c.example.com", TargetHost: "h", TargetPort: 8443, Enabled: true, TargetScheme: "https", TargetInsecureSkipVerify: true},
	}
	out1, _ := Render(cfg, routes, nil)
	out2, _ := Render(cfg, []Route{routes[2], routes[0], routes[1]}, nil)
	if string(out1) != string(out2) {
		t.Fatal("render is not order-independent")
	}
	var doc traefikDynamic
	if err := yaml.Unmarshal(out1, &doc); err != nil {
		t.Fatal(err)
	}
	if _, ok := doc.HTTP.Routers["ns-a"]; ok {
		t.Error("disabled route rendered")
	}
	if r := doc.HTTP.Routers["ns-b"]; r.Rule != "Host(`b.example.com`) && PathPrefix(`/api`)" || r.EntryPoints[0] != "web" || r.TLS != nil {
		t.Errorf("plain router: %+v", r)
	}
	if _, ok := doc.HTTP.Routers["ns-b-http"]; ok {
		t.Error("plain route must not get a redirect router")
	}
	if lb := doc.HTTP.Services["ns-c"].LoadBalancer; lb.ServersTransport != "ns-c-transport" || !doc.HTTP.ServersTransports["ns-c-transport"].InsecureSkipVerify {
		t.Errorf("skip-verify transport not wired: %+v", lb)
	}
}

func TestRender_EmptyProducesNoRouters(t *testing.T) {
	out, err := Render(Config{}, nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	if out != nil {
		t.Errorf("empty render must return nil (file gets removed), got:\n%s", out)
	}
	out, _ = Render(Config{}, []Route{{RouteID: "a", Domain: "a.example.com", TargetHost: "h", TargetPort: 1, Enabled: false}}, nil)
	if out != nil {
		t.Error("only-disabled routes must also render nil")
	}
}

func TestPublicURL(t *testing.T) {
	r := Route{Domain: "x.example.com", PathPrefix: "/app", TLS: true}
	if got := r.PublicURL(Config{Mode: ModeManaged, HTTPSPort: 8443}); got != "https://x.example.com:8443/app" {
		t.Errorf("got %q", got)
	}
	r.TLS = false
	if got := r.PublicURL(Config{Mode: ModeManaged, HTTPPort: 80}); got != "http://x.example.com/app" {
		t.Errorf("got %q", got)
	}
}

func TestConfigIsNode(t *testing.T) {
	cfg := Config{NodeMAC: "AA:BB:CC:DD:EE:FF", NodeSystemID: "machine-1"}
	if !cfg.IsNode("aa:bb:cc:dd:ee:ff", "", "") {
		t.Error("MAC match (case-insensitive) must identify the node")
	}
	if !cfg.IsNode("02:42:ac:11:00:02", "machine-1", "") {
		t.Error("stable system id must identify the node after a MAC change")
	}
	if !cfg.IsNode("02:42:ac:11:00:02", "", "machine-1") {
		t.Error("hardware uuid must identify the node")
	}
	if cfg.IsNode("02:42:ac:11:00:02", "other", "other") {
		t.Error("unrelated host must not match")
	}
	if (Config{}).IsNode("aa:bb:cc:dd:ee:ff", "machine-1", "") {
		t.Error("unset config must match nobody")
	}
}

func TestRender_PassthroughWildcard(t *testing.T) {
	cfg := Config{Enabled: true, Mode: ModeManaged, ACMEEnabled: true}
	routes := []Route{{
		RouteID: "pt1", Mode: RouteModePassthrough, Domain: "*.apps.example.com",
		TargetHost: "10.0.0.20", TargetPort: 80, TargetHTTPSPort: 443, Enabled: true,
	}}
	out, err := Render(cfg, routes, nil)
	if err != nil {
		t.Fatal(err)
	}
	var doc traefikDynamic
	if err := yaml.Unmarshal(out, &doc); err != nil {
		t.Fatalf("yaml: %v\n%s", err, out)
	}
	if doc.TCP == nil {
		t.Fatalf("tcp section missing:\n%s", out)
	}
	tr, ok := doc.TCP.Routers["ns-pt1-tls"]
	if !ok || tr.Rule != "HostSNIRegexp(`^[^.]+\\.apps\\.example\\.com$`)" || tr.EntryPoints[0] != "websecure" || tr.TLS == nil || !tr.TLS.Passthrough {
		t.Errorf("tcp router: %+v", tr)
	}
	if got := doc.TCP.Services["ns-pt1-tls"].LoadBalancer.Servers[0].Address; got != "10.0.0.20:443" {
		t.Errorf("tcp service address %q", got)
	}
	hr, ok := doc.HTTP.Routers["ns-pt1-http"]
	if !ok || hr.Rule != "HostRegexp(`^[^.]+\\.apps\\.example\\.com$`)" || hr.EntryPoints[0] != "web" || hr.TLS != nil {
		t.Errorf("http router: %+v", hr)
	}
	if got := doc.HTTP.Services["ns-pt1-http"].LoadBalancer.Servers[0].URL; got != "http://10.0.0.20:80" {
		t.Errorf("http service url %q", got)
	}
	if _, ok := doc.HTTP.Routers["ns-pt1"]; ok {
		t.Error("passthrough must not emit a terminating https router")
	}
	// Exact-name passthrough uses HostSNI/Host.
	routes[0].Domain = "cloud.example.com"
	out, _ = Render(cfg, routes, nil)
	if !strings.Contains(string(out), "HostSNI(`cloud.example.com`)") {
		t.Errorf("exact passthrough rule missing:\n%s", out)
	}
}
