#!/usr/bin/env bash
# Generate the Homebrew formula for node-stats from a SHA256SUMS file.
# Usage: gen-homebrew-formula.sh <version-without-leading-v> <sha256sums-path> > Formula/node-stats.rb
set -euo pipefail
VER="${1:?version (no leading v) required}"
SUMS="${2:?SHA256SUMS path required}"

sha_for() { awk -v f="$1" '$2 == f { print $1 }' "$SUMS" | head -1; }
DARWIN_ARM64="$(sha_for "node-stats_v${VER}_darwin_arm64.tar.gz")"
DARWIN_AMD64="$(sha_for "node-stats_v${VER}_darwin_amd64.tar.gz")"
LINUX_AMD64="$(sha_for "node-stats_v${VER}_linux_amd64.tar.gz")"
LINUX_ARM64="$(sha_for "node-stats_v${VER}_linux_arm64.tar.gz")"
# At minimum we need one mac + one linux arch, else the formula is unusable.
[ -n "$DARWIN_ARM64" ] || { echo "missing darwin_arm64 sha in $SUMS" >&2; exit 1; }
[ -n "$LINUX_AMD64" ]  || { echo "missing linux_amd64 sha in $SUMS"  >&2; exit 1; }

dl='https://github.com/LastSkywalkerER/node-page/releases/download/v#{version}'
block() { # <indent> <suffix> <sha>
  [ -n "$3" ] || return 0
  printf '%s%s\n%s  url "%s/node-stats_v#{version}_%s.tar.gz"\n%s  sha256 "%s"\n%s%s\n' \
    "$1" "$4" "$1" "$dl" "$2" "$1" "$3" "$1" 'end'
}

{
cat <<RUBY
# typed: false
# frozen_string_literal: true

# Homebrew formula for node-stats. Auto-generated by scripts/gen-homebrew-formula.sh
# on each release — do not edit by hand.
#
#   brew tap lastskywalkerer/node-page https://github.com/LastSkywalkerER/node-page
#   brew install node-stats
class NodeStats < Formula
  desc "Self-hosted system monitoring dashboard (CPU/mem/disk/net/Docker)"
  homepage "https://github.com/LastSkywalkerER/node-page"
  version "${VER}"
  license "MIT"

  on_macos do
RUBY
block "    " "darwin_arm64" "$DARWIN_ARM64" "on_arm do"
block "    " "darwin_amd64" "$DARWIN_AMD64" "on_intel do"
cat <<RUBY
  end

  on_linux do
RUBY
block "    " "linux_amd64" "$LINUX_AMD64" "on_intel do"
block "    " "linux_arm64" "$LINUX_ARM64" "on_arm do"
cat <<RUBY
  end

  def install
    bin.install "node-stats"
  end

  test do
    assert_match "System Stats", shell_output("#{bin}/node-stats -help")
  end
end
RUBY
}
