#!/usr/bin/env bash
#
# install.sh — install / update / uninstall node-stats via Docker Compose.
#
#   curl -fsSL https://raw.githubusercontent.com/LastSkywalkerER/node-page/main/scripts/install.sh | bash
#
# Subcommands (pass with `| bash -s -- <cmd>`):
#   install    (default) pull the image, write the stack, bring it up
#   update     pull the latest image and recreate
#   uninstall  stop the stack (add --purge to also delete data)
#
# Env overrides:  NODE_STATS_DIR (stack dir)   NODE_STATS_PORT (HTTP port)
#                 NODE_STATS_IMAGE (image ref)
#
set -euo pipefail

REPO="LastSkywalkerER/node-page"
RAW_BASE="https://raw.githubusercontent.com/${REPO}/main"
IMAGE="${NODE_STATS_IMAGE:-ghcr.io/lastskywalkerer/node-page:latest}"
HTTP_PORT="${NODE_STATS_PORT:-9090}"
PROJECT="node-stats"

if [ -n "${NODE_STATS_DIR:-}" ]; then
  STACK_DIR="$NODE_STATS_DIR"
elif [ "$(id -u)" = "0" ]; then
  STACK_DIR="/opt/node-stats"
else
  STACK_DIR="$HOME/.node-stats"
fi

green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
red() { printf '\033[31m%s\033[0m\n' "$*" >&2; }
die() {
  red "error: $*"
  exit 1
}

OS=""
ARCH=""
detect_platform() {
  case "$(uname -s)" in
  Linux) OS=linux ;;
  Darwin) OS=darwin ;;
  *) die "unsupported OS '$(uname -s)'. On Windows use the PowerShell installer (see README)." ;;
  esac
  case "$(uname -m)" in
  x86_64 | amd64) ARCH=amd64 ;;
  aarch64 | arm64) ARCH=arm64 ;;
  *) die "unsupported architecture '$(uname -m)' (need x86_64/amd64 or arm64)." ;;
  esac
  green "Detected ${OS}/${ARCH}"
}

require_docker() {
  command -v docker >/dev/null 2>&1 ||
    die "Docker not found. Install Docker Engine (Linux) or Docker Desktop (macOS): https://docs.docker.com/get-docker/"
  docker compose version >/dev/null 2>&1 ||
    die "Docker Compose v2 not found. Update Docker, or install the compose plugin: https://docs.docker.com/compose/install/"
  docker info >/dev/null 2>&1 ||
    die "Docker daemon not reachable. Start Docker and re-run."
}

# fetch URL to stdout (curl or wget), empty on failure (caller falls back).
fetch() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$1" 2>/dev/null || true
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- "$1" 2>/dev/null || true
  fi
}

prepare_stack_dir() {
  mkdir -p "$STACK_DIR/data/docker"
  # .env.agent MUST be a regular file: it is bind-mounted to /app/.env and the
  # wizard writes secrets/config there. A directory mount silently swallows that.
  if [ -d "$STACK_DIR/.env.agent" ]; then
    die "$STACK_DIR/.env.agent is a directory — remove it (rmdir '$STACK_DIR/.env.agent') and re-run."
  fi
  [ -f "$STACK_DIR/.env.agent" ] || : >"$STACK_DIR/.env.agent"
  chmod 600 "$STACK_DIR/.env.agent" 2>/dev/null || true
}

write_env() {
  local env="$STACK_DIR/.env"
  if [ -f "$env" ]; then
    # Preserve existing settings; just ensure the stack dir is current.
    if grep -q '^NODE_STATS_STACK_HOST_DIR=' "$env"; then
      sed -i.bak "s#^NODE_STATS_STACK_HOST_DIR=.*#NODE_STATS_STACK_HOST_DIR=${STACK_DIR}#" "$env" && rm -f "$env.bak"
    else
      echo "NODE_STATS_STACK_HOST_DIR=${STACK_DIR}" >>"$env"
    fi
    return
  fi
  cat >"$env" <<EOF
# node-stats stack configuration (Compose variable substitution).
# JWT_SECRET / REFRESH_SECRET are generated by the setup wizard into .env.agent.
NODE_STATS_IMAGE=${IMAGE}
NODE_STATS_PORT=${HTTP_PORT}
NODE_STATS_STACK_HOST_DIR=${STACK_DIR}
COMPOSE_PROJECT_NAME=${PROJECT}
GIN_MODE=release
EOF
  chmod 600 "$env" 2>/dev/null || true
}

write_compose() {
  # Base compose: generate from the image so it always matches the controller's
  # output; fall back to the committed template if the run fails.
  if ! docker run --rm -e NODE_STATS_IMAGE="$IMAGE" "$IMAGE" gen-compose >"$STACK_DIR/docker-compose.yml" 2>/dev/null ||
    [ ! -s "$STACK_DIR/docker-compose.yml" ]; then
    yellow "gen-compose unavailable; fetching the base template"
    fetch "${RAW_BASE}/install/docker-compose.base.yml" >"$STACK_DIR/docker-compose.yml"
    [ -s "$STACK_DIR/docker-compose.yml" ] || die "could not obtain a base docker-compose.yml"
  fi

  # OS host-capabilities override (Linux gets pid/ipc host; macOS none).
  local src="docker-compose.macos.yml"
  [ "$OS" = linux ] && src="docker-compose.linux.yml"
  local override
  override="$(fetch "${RAW_BASE}/install/${src}")"
  if [ -n "$override" ]; then
    printf '%s\n' "$override" >"$STACK_DIR/docker-compose.override.yml"
  elif [ "$OS" = linux ]; then
    cat >"$STACK_DIR/docker-compose.override.yml" <<'EOF'
services:
  node-stats:
    pid: host
    ipc: host
EOF
  else
    printf 'services:\n  node-stats: {}\n' >"$STACK_DIR/docker-compose.override.yml"
  fi

  if [ "$OS" != linux ]; then
    yellow "Note: Docker Desktop runs in a VM — host CPU/mem/disk metrics reflect the VM, not your machine."
    yellow "For full host metrics on macOS/Windows, use the native binary (see README)."
  fi
}

compose() { (cd "$STACK_DIR" && docker compose "$@"); }

cmd_install() {
  detect_platform
  require_docker
  green "Installing node-stats into ${STACK_DIR}"
  prepare_stack_dir
  green "Pulling ${IMAGE} ..."
  if ! docker pull "$IMAGE" >/dev/null 2>&1; then
    docker image inspect "$IMAGE" >/dev/null 2>&1 || die "failed to pull ${IMAGE} (and no local copy present)"
    yellow "pull failed; using the local ${IMAGE}"
  fi
  write_env
  write_compose
  green "Starting the stack ..."
  compose pull >/dev/null 2>&1 || true
  compose up -d || die "docker compose up failed"
  green ""
  green "node-stats is up → http://localhost:${HTTP_PORT}"
  green "Open it in a browser to finish setup (create the admin, pick the database)."
  yellow "Manage later: curl -fsSL ${RAW_BASE}/scripts/install.sh | bash -s -- update | uninstall"
  yellow "Stack dir: ${STACK_DIR}"
}

cmd_update() {
  require_docker
  [ -f "$STACK_DIR/docker-compose.yml" ] || die "no stack at ${STACK_DIR}; run install first."
  green "Updating node-stats in ${STACK_DIR} ..."
  compose pull
  compose up -d
  green "Update complete → http://localhost:${HTTP_PORT}"
}

cmd_uninstall() {
  [ -f "$STACK_DIR/docker-compose.yml" ] || die "no stack at ${STACK_DIR}"
  green "Stopping node-stats ..."
  compose down || true
  if [ "${1:-}" = "--purge" ]; then
    yellow "Purging data at ${STACK_DIR}/data ..."
    rm -rf "${STACK_DIR}/data"
  else
    yellow "Data kept at ${STACK_DIR}/data (use 'uninstall --purge' to delete)."
  fi
}

case "${1:-install}" in
install) cmd_install ;;
update) cmd_update ;;
uninstall) cmd_uninstall "${2:-}" ;;
-h | --help | help) echo "usage: install.sh {install|update|uninstall [--purge]}" ;;
*) die "unknown command '${1}' (use install|update|uninstall)" ;;
esac
