#!/usr/bin/env python3
"""Convert a Nginx Proxy Manager database into a Traefik dynamic config that the
node-stats gateway can import (Gateway tab → Import, or drop the output as
<data dir>/gateway-import.yml on any node).

    python3 scripts/npm-to-traefik.py /DATA/AppData/nginxproxymanager/data/database.sqlite > gateway-import.yml

Mapping (per NPM proxy host):
  domain_names[0] → Host(), the rest → aliases in the same rule
  forward_scheme://forward_host:forward_port → the service url
  certificate_id != 0 → websecure router with tls (certResolver le) + the
      http→https companion; ssl_forced is implied (the gateway always redirects
      TLS routes) — use --no-tls host1,host2 for Cloudflare "Flexible" origins
  hsts_enabled → headers middleware with stsSeconds (+ subdomains)
  block_exploits → ignored (Traefik has no equivalent; the gateway's client
      blocking / rate limits cover the same ground)
  access lists → basicAuth (existing htpasswd hashes) + ipAllowList (allow rules)
  redirection hosts → redirectRegex on noop@internal
  streams → tcp/udp routers on ns-<proto>-<port> entrypoints
  advanced_config → printed as a comment on the router; translate by hand
      (locations are usually extra PathPrefix routers to the same or another
      service — see docs/GATEWAY.md, "Routes")
"""
import argparse
import json
import re
import sqlite3
import sys


def q(s):
    return "`" + s + "`"


def yaml_str(s):
    return json.dumps(s)  # a JSON string is valid YAML


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("db", help="path to NPM database.sqlite (read-only)")
    ap.add_argument("--no-tls", default="", help="comma-separated hostnames to emit as plain http (Cloudflare Flexible origins)")
    ap.add_argument("--skip", default="", help="comma-separated hostnames to leave out (e.g. NPM's own admin host)")
    ap.add_argument("--rewrite", action="append", default=[], help="HOST=NEWHOST[:PORT] — replace an upstream host (e.g. 127.0.0.1=host.docker.internal)")
    args = ap.parse_args()
    no_tls = {h.strip().lower() for h in args.no_tls.split(",") if h.strip()}
    skip = {h.strip().lower() for h in args.skip.split(",") if h.strip()}
    rewrites = {}
    for rw in args.rewrite:
        k, _, v = rw.partition("=")
        rewrites[k.strip()] = v.strip()

    c = sqlite3.connect(f"file:{args.db}?mode=ro", uri=True)
    c.row_factory = sqlite3.Row
    out = ["# Generated by scripts/npm-to-traefik.py from Nginx Proxy Manager — review, then import into the node-stats gateway.", ""]
    routers, services, middlewares, transports = {}, {}, {}, {}
    tcp_routers, tcp_services, udp_routers, udp_services = {}, {}, {}, {}
    notes = []

    def access_list(alid, name):
        mws = []
        if not alid:
            return mws
        auths = [dict(r) for r in c.execute("select username,password from access_list_auth where access_list_id=? and is_deleted=0", (alid,))]
        if auths:
            # NPM stores plain passwords; hash them like htpasswd would (bcrypt via Traefik-compatible $2y$)
            try:
                import bcrypt  # type: ignore
                users = [f"{a['username']}:{bcrypt.hashpw(a['password'].encode(), bcrypt.gensalt()).decode()}" for a in auths]
            except ImportError:
                import crypt
                users = [f"{a['username']}:{crypt.crypt(a['password'], crypt.mksalt(crypt.METHOD_MD5))}" for a in auths]
                notes.append(f"{name}: python 'bcrypt' module missing — basic-auth hashes emitted as MD5-crypt (works, weaker)")
            middlewares[f"{name}-auth"] = {"basicAuth": {"users": users}}
            mws.append(f"{name}-auth")
        allow = [r["address"] for r in c.execute("select address,directive from access_list_client where access_list_id=? and is_deleted=0", (alid,)) if r["directive"] == "allow"]
        if allow:
            middlewares[f"{name}-ipallow"] = {"ipAllowList": {"sourceRange": allow}}
            mws.append(f"{name}-ipallow")
        return mws

    def target(host, port):
        if host in rewrites:
            nh = rewrites[host]
            if ":" in nh:
                nh, port = nh.rsplit(":", 1)
            return nh, int(port)
        return host, int(port)

    for r in c.execute("select * from proxy_host where is_deleted=0 order by id"):
        domains = [d.lower() for d in json.loads(r["domain_names"])]
        if not domains or domains[0] in skip:
            continue
        name = re.sub(r"[^a-z0-9-]", "-", domains[0])
        host, port = target(r["forward_host"], r["forward_port"])
        scheme = r["forward_scheme"]
        rule = " || ".join(f"Host({q(d)})" for d in domains)
        if len(domains) > 1:
            rule = f"({rule})"
        services[name] = {"loadBalancer": {"servers": [{"url": f"{scheme}://{host}:{port}"}]}}
        if scheme == "https":
            transports[f"{name}-transport"] = {"insecureSkipVerify": True}
            services[name]["loadBalancer"]["serversTransport"] = f"{name}-transport"
        mws = access_list(r["access_list_id"], name)
        tls = bool(r["certificate_id"]) and domains[0] not in no_tls
        if r["hsts_enabled"] and tls:
            middlewares[f"{name}-headers"] = {"stsSeconds": 63072000, "stsIncludeSubdomains": bool(r["hsts_subdomains"])}
            middlewares[f"{name}-headers"] = {"headers": middlewares[f"{name}-headers"]}
            mws.append(f"{name}-headers")
        comment = []
        if not r["enabled"]:
            comment.append("disabled in NPM")
        if r["block_exploits"]:
            comment.append("NPM 'block exploits' had no Traefik equivalent (use gateway rate limits / client blocks)")
        if (r["advanced_config"] or "").strip():
            comment.append("ADVANCED CONFIG needs manual translation:")
            comment += ["    " + ln for ln in r["advanced_config"].splitlines()]
        router = {"rule": rule, "service": name, "entryPoints": ["websecure" if tls else "web"]}
        if mws:
            router["middlewares"] = mws
        if tls:
            router["tls"] = {"certResolver": "le"}
            middlewares[f"{name}-redirect"] = {"redirectScheme": {"scheme": "https", "permanent": True}}
            routers[f"{name}-http"] = {"rule": rule, "service": name, "entryPoints": ["web"], "middlewares": [f"{name}-redirect"]}
        routers[name] = router
        if comment:
            notes.append(f"{domains[0]}: " + " | ".join(comment[:1]) + ("" if len(comment) == 1 else ""))
            router["_comment"] = comment

    for r in c.execute("select * from redirection_host where is_deleted=0 order by id"):
        domains = [d.lower() for d in json.loads(r["domain_names"])]
        if not domains or domains[0] in skip:
            continue
        name = "redirect-" + re.sub(r"[^a-z0-9-]", "-", domains[0])
        rule = " || ".join(f"Host({q(d)})" for d in domains)
        if len(domains) > 1:
            rule = f"({rule})"
        dest = f"{r['forward_scheme'] if r['forward_scheme'] != '$scheme' else 'https'}://{r['forward_domain_name']}"
        permanent = int(r["forward_http_code"] or 301) in (301, 308)
        if r["preserve_path"]:
            mw = {"regex": "^https?://[^/]+(/.*)?$", "replacement": dest + "${1}", "permanent": permanent}
        else:
            mw = {"regex": "^.*$", "replacement": dest, "permanent": permanent}
        middlewares[name] = {"redirectRegex": mw}
        tls = bool(r["certificate_id"])
        routers[name] = {"rule": rule, "service": "noop@internal", "entryPoints": ["web"], "middlewares": [name]}
        if tls:
            routers[name + "-tls"] = {"rule": rule, "service": "noop@internal", "entryPoints": ["websecure"], "middlewares": [name], "tls": {"certResolver": "le"}}

    for r in c.execute("select * from stream where is_deleted=0 order by id"):
        host, port = target(r["forwarding_host"], r["forwarding_port"])
        for proto, on in (("tcp", r["tcp_forwarding"]), ("udp", r["udp_forwarding"])):
            if not on:
                continue
            name = f"stream-{proto}-{r['incoming_port']}"
            ep = f"ns-{proto}-{r['incoming_port']}"
            svc = {"loadBalancer": {"servers": [{"address": f"{host}:{port}"}]}}
            if proto == "tcp":
                tcp_routers[name] = {"rule": "HostSNI(`*`)", "service": name, "entryPoints": [ep]}
                tcp_services[name] = svc
            else:
                udp_routers[name] = {"service": name, "entryPoints": [ep]}
                udp_services[name] = svc

    def emit(v, indent):
        """Minimal YAML emitter for dict/list/str/bool/int (no PyYAML dependency)."""
        pad = " " * indent
        if isinstance(v, dict):
            for k, val in v.items():
                if k == "_comment":
                    continue
                if isinstance(val, (dict, list)) and val:
                    if isinstance(val, dict) and val.get("_comment"):
                        for ln in val["_comment"]:
                            out.append(f"{pad}# {ln}")
                    out.append(f"{pad}{k}:")
                    emit(val, indent + 2)
                else:
                    out.append(f"{pad}{k}: {scalar(val)}")
        elif isinstance(v, list):
            for item in v:
                if isinstance(item, dict):
                    first = True
                    for k, val in item.items():
                        lead = f"{pad}- " if first else f"{pad}  "
                        first = False
                        if isinstance(val, (dict, list)) and val:
                            out.append(f"{lead}{k}:")
                            emit(val, indent + 4)
                        else:
                            out.append(f"{lead}{k}: {scalar(val)}")
                else:
                    out.append(f"{pad}- {scalar(item)}")

    def scalar(v):
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, (int, float)):
            return str(v)
        if isinstance(v, dict) and not v:
            return "{}"
        if isinstance(v, list) and not v:
            return "[]"
        return yaml_str(str(v))

    doc = {}
    if routers:
        doc["http"] = {"routers": routers, "services": services}
        if middlewares:
            doc["http"]["middlewares"] = middlewares
        if transports:
            doc["http"]["serversTransports"] = transports
    if tcp_routers:
        doc["tcp"] = {"routers": tcp_routers, "services": tcp_services}
    if udp_routers:
        doc["udp"] = {"routers": udp_routers, "services": udp_services}
    emit(doc, 0)
    if notes:
        out.insert(2, "# Review notes:")
        for n in notes:
            out.insert(3, "#   " + n)
    print("\n".join(out))
    if not routers and not tcp_routers and not udp_routers:
        print("nothing to convert", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
