package setup

import (
	"fmt"
	"strings"
)

// DB mode identifiers carried in the desired-state descriptor and used by
// BuildComposeContent to decide whether to inject a Postgres service.
const (
	DBModeSQLite           = "sqlite"
	DBModePostgresManaged  = "postgres-managed"  // node-stats runs a `db` postgres container
	DBModePostgresExternal = "postgres-external" // operator points at an existing server
)

// DefaultImage is the published image the generated compose pulls. Overridable
// per-deployment via the NODE_STATS_IMAGE compose variable.
const DefaultImage = "ghcr.io/lastskywalkerer/node-page:latest"

// DesiredState is the descriptor the running app writes to the shared data
// volume (desired-state.json) and the controller reads to (re)generate and
// apply the docker-compose stack. It is the single source of truth for the
// DB topology and the target image. The app↔controller contract — keep the
// JSON tags stable.
type DesiredState struct {
	// Generation is a monotonically increasing counter; together with the
	// content hash it lets the controller skip already-applied states.
	Generation int `json:"generation"`

	// DBMode is one of the DBMode* constants.
	DBMode string `json:"db_mode"`

	// DBDSN is the app's connection string for the postgres modes (the GORM
	// keyword form; host=db for managed). Empty for sqlite (a fixed in-volume
	// path is used). The controller writes this into the app's DB_DSN env so a
	// DB change actually takes effect on recreate.
	DBDSN string `json:"db_dsn"`

	// DB carries the managed-Postgres provisioning details (mode
	// postgres-managed only) — used to configure the injected `db` container.
	DB DBProvision `json:"db"`

	// Image is the container image both services run (defaults to DefaultImage).
	Image string `json:"image"`

	// PullBeforeApply asks the controller to `docker compose pull` the app
	// service before recreating it (used by the auto-updater).
	PullBeforeApply bool `json:"pull_before_apply"`

	// ManagedExternally disables controller mutation entirely (Dokploy/Traefik).
	ManagedExternally bool `json:"managed_externally"`
}

// DBProvision configures the managed Postgres container.
type DBProvision struct {
	Name     string `json:"name"`
	User     string `json:"user"`
	Password string `json:"password"`
}

// BuildComposeContent renders the canonical base docker-compose.yml from the
// desired state. It mirrors the string-building style of buildEnvFileContent.
//
// Design notes:
//   - Auth secrets (JWT_SECRET/REFRESH_SECRET) are deliberately NOT in the app
//     `environment:` — they load from the bind-mounted .env.agent (/app/.env)
//     the wizard writes, so they survive rebuilds and aren't shadowed by empty
//     compose vars (same pattern as RAFT_*).
//   - DB connection (DB_TYPE/DB_DSN) IS in the app `environment:` and is
//     controller-managed: this is what makes a DB switch take effect on recreate
//     (compose detects the env change) and keeps the bootstrap sqlite DB in the
//     persisted /app/data volume.
//   - Host capabilities (pid/ipc/network_mode host, Linux-only) live in an
//     installer-owned docker-compose.override.yml, which compose auto-merges;
//     the controller never touches the override.
//   - The controller identity-mounts the host stack dir at the SAME path
//     (${NODE_STATS_STACK_HOST_DIR}) so the docker CLI's relative bind paths
//     resolve to real host paths when it talks to the host daemon.
func BuildComposeContent(ds DesiredState) string {
	image := strings.TrimSpace(ds.Image)
	if image == "" {
		image = DefaultImage
	}
	imageRef := fmt.Sprintf("${NODE_STATS_IMAGE:-%s}", image)
	managed := ds.DBMode == DBModePostgresManaged

	var b strings.Builder
	w := func(s string) { b.WriteString(s); b.WriteString("\n") }

	w("# Generated by node-stats — do NOT edit by hand.")
	w("# The controller regenerates this file when the setup wizard changes the")
	w("# database/topology. Host capabilities (pid/ipc/network) live in")
	w("# docker-compose.override.yml, which Compose auto-merges and which this")
	w("# file never overwrites.")
	w("services:")

	// --- app service ---------------------------------------------------------
	w("  node-stats:")
	w("    image: " + imageRef)
	w("    ports:")
	w(`      - "${NODE_STATS_PORT:-9090}:9090"`)
	// Publish the Raft port so peers on other hosts can reach this node's
	// consensus transport (the app binds :7000 inside; the host port is
	// overridable per-instance via NODE_STATS_RAFT_PORT for multi-instance hosts).
	w(`      - "${NODE_STATS_RAFT_PORT:-7000}:7000"`)
	w("    volumes:")
	w("      - ./.env.agent:/app/.env")
	w("      - ./data/docker:/app/data")
	// Docker socket (read-only) so the Docker collector / Applications view can
	// query the daemon. The controller mounts it read-write for compose control.
	w("      - /var/run/docker.sock:/var/run/docker.sock:ro")
	w("      - /:/host:ro")
	w("    extra_hosts:")
	w(`      - "host.docker.internal:host-gateway"`)
	if managed {
		w("    depends_on:")
		w("      db:")
		w("        condition: service_healthy")
	}
	w("    environment:")
	w("      - ADDR=:9090")
	w("      - GIN_MODE=${GIN_MODE:-release}")
	// DB connection (controller-managed; JWT/REFRESH come from .env.agent).
	if ds.DBMode == DBModeSQLite {
		w("      - DB_TYPE=sqlite")
		w("      - DB_DSN=/app/data/stats.db")
	} else {
		w("      - DB_TYPE=postgres")
		// In Compose's `environment:` list form the value is everything after the
		// first '='; it must NOT be quoted (quotes become literal). Spaces in the
		// keyword DSN are fine; only '$' needs escaping (Compose interpolation).
		w("      - DB_DSN=" + composeEnvValue(ds.DBDSN))
	}
	w("      - HOST_PROC=/host/proc")
	w("      - HOST_SYS=/host/sys")
	w("      - HOST_ETC=/host/etc")
	w("      - HOST_ROOT=/host")
	w("      - NODE_HOST_ALIAS=host.docker.internal")
	// Host outbound IPv4 detected by the installer (the container can't see it
	// behind a bridge network); empty falls back to the in-container probe.
	w("      - NODE_STATS_IPV4=${NODE_STATS_IPV4:-}")
	// Optional display hostname — distinguishes nodes that share a host
	// (e.g. several instances on one Docker VM, whose OS hostname collides).
	w("      - NODE_STATS_HOSTNAME=${NODE_STATS_HOSTNAME:-}")
	w("    restart: unless-stopped")

	// --- managed postgres (optional) -----------------------------------------
	if managed {
		name := orDefault(ds.DB.Name, "node_stats")
		user := orDefault(ds.DB.User, "node_stats")
		pass := ds.DB.Password
		w("  db:")
		w("    image: postgres:16-alpine")
		w("    restart: unless-stopped")
		w("    environment:")
		w("      - POSTGRES_DB=" + name)
		w("      - POSTGRES_USER=" + user)
		w("      - POSTGRES_PASSWORD=" + composeEnvValue(pass))
		w("    volumes:")
		w("      - pgdata:/var/lib/postgresql/data")
		w("    healthcheck:")
		w(fmt.Sprintf(`      test: ["CMD-SHELL", "pg_isready -U %s -d %s"]`, user, name))
		w("      interval: 5s")
		w("      timeout: 3s")
		w("      retries: 10")
	}

	// --- controller sidecar --------------------------------------------------
	w("  node-stats-controller:")
	w("    image: " + imageRef)
	w(`    command: ["controller"]`)
	w("    volumes:")
	w("      - /var/run/docker.sock:/var/run/docker.sock")
	// Identity mount: same path inside the controller as on the host so the
	// docker CLI's relative bind-mount sources resolve to real host paths.
	w("      - ${NODE_STATS_STACK_HOST_DIR}:${NODE_STATS_STACK_HOST_DIR}")
	w("    environment:")
	w("      - NODE_STATS_STACK_DIR=${NODE_STATS_STACK_HOST_DIR}")
	w("      - NODE_STATS_DATA_DIR=${NODE_STATS_STACK_HOST_DIR}/data/docker")
	w("      - NODE_STATS_APP_SERVICE=node-stats")
	// The controller drives `docker compose -p <project>`; it must match the
	// stack's project so multi-instance hosts don't cross-manage each other.
	w("      - NODE_STATS_PROJECT=${COMPOSE_PROJECT_NAME:-node-stats}")
	w("    restart: unless-stopped")

	// --- top-level volumes ---------------------------------------------------
	if managed {
		w("volumes:")
		w("  pgdata:")
	}

	return b.String()
}

// orDefault returns v trimmed, or def when empty.
func orDefault(v, def string) string {
	if strings.TrimSpace(v) == "" {
		return def
	}
	return strings.TrimSpace(v)
}

// composeEnvValue escapes a value for use in a Compose `environment:` list item
// (`- KEY=VALUE`). The value must stay unquoted there (surrounding quotes become
// literal); only '$' needs doubling so Compose doesn't treat it as interpolation.
func composeEnvValue(s string) string {
	return strings.ReplaceAll(s, "$", "$$")
}
